### ISSUE TITLE
Video returned by YouTube isn't what was requested

### ISSUE THREAD

**Issue by AndrewStoddard** [lavalink-devs/youtube-source#9]
When searching for a youtube song the search works, but then errors on getting the video. 

[lavalinklogs.txt](https://github.com/lavalink-devs/youtube-source/files/15326446/lavalinklogs.txt)

Using the latest lavalink package ghcr.io/lavalink-devs/lavalink:latest

```
plugins:
  youtube:
    enabled: true # Whether this source can be used.
    allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
    allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
    allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
    # The clients to use for track loading. See below for a list of valid clients.
    # Clients are queried in the order they are given (left-to-right)
    clients: ["MUSIC", "WEB", "ANDROID"]
server: # REST and WS server
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.2.0"
      repository: "https://maven.lavalink.dev/releases" 
      snapshot: false
  pluginsDir: "./plugins"
  server:
    password: "redacted"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: true
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Minimum>    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is the best quality but i>    resamplingQuality: HIGH # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses >    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if it does not ret>    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read fr>    youtubePlaylistLoadLimit: 100 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played >      email: "redacted" # Email of Google account
      password: "redacted" # Password of Google account
metrics:
  prometheus:
    enabled: true
    endpoint: /metrics
sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value

#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
```
